# Generated by Django 3.2.3 on 2021-10-27 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=45)),
                ('cat_eye', models.CharField(blank=True, max_length=45, null=True)),
                ('cat_hair', models.CharField(blank=True, max_length=45, null=True)),
                ('cat_socks', models.CharField(blank=True, max_length=45, null=True)),
                ('cat_locate', models.CharField(blank=True, max_length=45, null=True)),
                ('cat_mom', models.IntegerField(default=0)),
                ('cat_tnr', models.IntegerField(default=0)),
                ('cat_prefer', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_special', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_prof_img', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_image', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_xlocation', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_ylocation', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 23, 59, 26, 767865))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('cat_id', models.IntegerField()),
                ('is_active', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 23, 59, 26, 768404))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pair',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('is_active', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 23, 59, 26, 769184))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pLike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('image', models.TextField(blank=True)),
                ('is_active', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 23, 59, 26, 768805))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('content', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 10, 27, 23, 59, 26, 769546))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reply',
                'managed': False,
            },
        ),
    ]
