# Generated by Django 3.2.7 on 2021-10-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_cats_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatsCat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cats_cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=45, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('user_image', models.CharField(blank=True, max_length=45, null=True)),
                ('ser_state', models.CharField(blank=True, max_length=45, null=True)),
                ('user_city', models.CharField(blank=True, max_length=45, null=True)),
                ('popup', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userfollowcat',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, max_length=45, null=True)),
                ('user_name', models.CharField(blank=True, max_length=45, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userfollowcat',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'managed': False},
        ),
    ]
