# Generated by Django 3.2.7 on 2021-10-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20211003_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatsCat',
        ),
        migrations.AlterModelTable(
            name='cat',
            table='cat',
        ),
    ]
