# Generated by Django 3.2.7 on 2021-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20211003_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatsCat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cats_cat',
                'managed': False,
            },
        ),
    ]
