# Generated by Django 3.2.7 on 2021-10-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_catscat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatsCat',
        ),
    ]
