# Generated by Django 3.2.7 on 2021-10-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_delete_catscat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('upassword', models.CharField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('is_active', models.IntegerField()),
                ('is_admin', models.IntegerField()),
                ('is_superuser', models.IntegerField()),
                ('is_staff', models.IntegerField()),
                ('popup', models.IntegerField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('pair_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pair',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('is_active', models.IntegerField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_active', models.IntegerField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reply',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Catuser',
        ),
        migrations.DeleteModel(
            name='Userfollowcat',
        ),
    ]
