# Generated by Django 3.2.7 on 2021-10-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_auto_20211009_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuser',
        ),
    ]
