# Generated by Django 3.2.7 on 2021-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('upassword', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('is_admin', models.IntegerField(default=0)),
                ('is_superuser', models.IntegerField(default=0)),
                ('is_staff', models.IntegerField(default=0)),
                ('popup', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuser',
            },
        ),
    ]
