# Generated by Django 3.2.7 on 2021-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='is_staff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='is_superuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='popup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='upassword',
            field=models.TextField(),
        ),
    ]
